@startuml

!theme plain


state Error {
    Error : Error Info
    Error : Error Logging

}

state WebServer {
    WaitForClient --> SendSite : Client Connect
    SendSite --> WaitForClient : Client Disconnect
    SendSite --> SendSite : Download Data
}

state Startup{
    Startup : Init SD-Card
    Startup : Init Sensor
    Startup : Init GPS
    Startup : Init Web Server

}

state Ready {
    Ready : LED Green
}


state Record {

    Record : LED Red

    CreateNewFile --> ReadData
    ReadData --> SaveData
    SaveData --> ReadData

    SaveData --> Ready : Stop Record
}

state Calibration{
    Calibration : LED Blue
    Calibration : Calibrate IMU
}





[*] --> Startup

Startup --> WebServer
Startup --> Ready
Startup --> Error : Init Error



Ready --> Calibration : Start Calibration
Ready --> Record : Start Record
Ready --> [*] : Shutdown

Record --> Error : Record Error

Calibration --> Ready : End Calibration
Calibration --> Error : Calibration Error


Error --> [*] : Shutdown




















@enduml